import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { DEFAULT_AVATAR_COLOR } from "@/lib/auth/avatar-palette";
import { OnboardingFlow } from "./OnboardingFlow";

export const metadata = { title: "Welcome - mindlap" };

export default async function OnboardingPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const { data: profile } = await supabase
    .from("profiles")
    .select("username, theme_pref, avatar_color, onboarded_at")
    .eq("id", user.id)
    .single();

  // The proxy normally redirects already-onboarded users away, but keep a
  // server-side guard for direct hits (defense in depth).
  if (profile?.onboarded_at) redirect("/today");

  // friend_code is generated by handle_new_user trigger and lives in
  // profile_secrets (owner-only SELECT). Surface it on step 3 so the user
  // can copy + share before they hit /today.
  const { data: secret } = await supabase
    .from("profile_secrets")
    .select("friend_code")
    .eq("user_id", user.id)
    .single();

  return (
    <main style={{ maxWidth: 480, margin: "0 auto", padding: "64px 32px" }}>
      <h1>Welcome to mindlap</h1>
      <p style={{ color: "var(--muted)", marginBottom: 32 }}>
        Three quick steps and you&apos;re playing.
      </p>
      <OnboardingFlow
        suggestedUsername={profile?.username ?? ""}
        initialTheme={(profile?.theme_pref as "light" | "dark" | "system") ?? "system"}
        avatarColor={profile?.avatar_color ?? DEFAULT_AVATAR_COLOR}
        friendCode={secret?.friend_code ?? ""}
      />
    </main>
  );
}
